from enum import Enum

class ResponseSignal(Enum):

    FILE_VALIDATED_SUCCES = "FILE_VALIDATED_SUCCES"
    FILE_TYPE_NOT_SUPPORTED = "FILE_TYPE_NOT_SUPPORTED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_UPLOADED_SUCCES = "FILE_UPLOADED_SUCCES"
    FILE_UPLOADED_FAILD = "FILE_UPLOADED_FAILD"
    FILE_EXTENTION_NOT_ALLOWED = "File_Extention_Not_Allowed"


    SENTIMENT_TEXT_FAILD = "SENTIMENT_TEXT_FAILD"